### ISSUE TITLE
X data must have 1500 columns.

### ISSUE THREAD

**Issue by bashidagha** [Computational-Imaging-Lab-IITM/HAR-DVS#1]
During Run the code "run_dvs.m"
in svm_loo.m on line 191:
`    [pred_xy_xt_yt, score_xy_xt_yt, cost_xy_xt_yt] = predict(svmc_xy_xt_yt, [test_features_MMxy, test_features_MMxt, test_features_MMyt]);`

I stop on error 
```
Parallel pool using the 'local' profile is shutting down.
Error using
classreg.learning.classif.CompactClassificationECOC/predictEmptyX
(line 133)
X data must have 1500 columns.

Error in
classreg.learning.classif.CompactClassificationECOC/predict (line
334)
                [varargout{1:max(1,nargout)}] =
                predictEmptyX(this,X);

Error in svm_loo (line 191)
    [pred_xy_xt_yt, score_xy_xt_yt, cost_xy_xt_yt] =
    predict(svmc_xy_xt_yt, [test_features_MMxy,
    test_features_MMxt, test_features_MMyt]);

Error in run_dvs (line 77)
    [accuracy_xy_xt_yt, accuracy_xy_xt_yt_MBHx_MBHy,
    accuracy_xy_xt_yt_HoF, accuracy_HoG, accuracy_HoF,
    accuracy_MBHx_MBHy, accuracy_xy, accuracy_xt, accuracy_yt,
    confusion_xy_xt_yt, confusion_xy_xt_yt_MBHx_MBHy,
    confusion_xy_xt_yt_HoF, confusion_HoG, confusion_HoF,
    confusion_MBHx_MBHy, confusion_xy, confusion_xt,
    confusion_yt] = svm_loo(encoded_data_path, num_classes);
 
```

Can anyone help me,please?

**Comment by bashidagha** [comment]
It's Solved!
It was because my test folder was empty!
I just copy some of encoded data in the test folder.
Good Result!

**Comment by xlj199** [comment]
> It's Solved!
> It was because my test folder was empty!
> I just copy some of encoded data in the test folder.
> Good Result!

Hello, I'm also running this code right now. There are some problems.
Could you please send me a copy of the code you used to run? Thank you very much!
e-mail address :2580703451@qq.com
