### ISSUE TITLE
 dense_features_*.mat files in code ???

### ISSUE THREAD

**Issue by xlj199** [Computational-Imaging-Lab-IITM/HAR-DVS#2]
Thank you so much for sharing your code.
I found a missing file( dense_features_*.mat) in the course of running. Is this file to be generated through dense_trajectory_release_v1.2.

**Comment by chinnichaitanya** [comment]
Hello @xlj199 sorry about the late reply. You can please refer to the [`run_dense.sh`](https://github.com/Computational-Imaging-Lab-IITM/HAR-DVS/blob/master/lib/run_dense.sh) file. It generates these dense features. 

As you've pointed out, these would be generated through the dense_trajectory module.
