### ISSUE TITLE
Lack of .mat file(_HoG.mat、_HoF.mat、_MBHx.mat and so on) generation？？

### ISSUE THREAD

**Issue by xlj199** [Computational-Imaging-Lab-IITM/HAR-DVS#3]

**Comment by chinnichaitanya** [comment]
Hello @xlj199, these features matrices are generated through the [`generate_codebook.m`](https://github.com/Computational-Imaging-Lab-IITM/HAR-DVS/blob/master/lib/generate_codebook.m#L188-L193) file. 

We first extract the dense features using [`run_dense.sh`](https://github.com/Computational-Imaging-Lab-IITM/HAR-DVS/blob/master/lib/run_dense.sh) and then generate the codebooks for motion-maps as well as HoG, HoF and MBH features.
