### ISSUE TITLE
Thanks for the code，but the results were less than satisfactory

### ISSUE THREAD

**Issue by xlj199** [Computational-Imaging-Lab-IITM/HAR-DVS#4]
hi，That's what I got the accuracy_*.mat about 0.2 only , confusion_*.mat about only 0.02(On the diagonal),and summed_confusion_* .mat about only 0.5 (On the diagonal).
1.What does this three parameter representation mean
2.Did I get it wrong? Why did it happen?(IITM_DVS_10)How to check the correct accuracy?

**Comment by chinnichaitanya** [comment]
Hello @xlj199. Thank you for going through the code and trying it out.
