### ISSUE TITLE
confusion_.mat、 summed_confusion_* .mat data means ?

### ISSUE THREAD

**Issue by xlj199** [Computational-Imaging-Lab-IITM/HAR-DVS#5]
That's what I got the accuracy_.mat about 0.2 only , confusion_.mat about only 0.02(On the diagonal),and summed_confusion_* .mat about only 0.5 (On the diagonal).
What does this three parameter representation mean?

**Comment by chinnichaitanya** [comment]
Accuracy is for storing the accuracies in each fold using various features as input.
The confusion matrix is for storing the confusion matrix in each fold with various input features.
The summed confusion matrix is for fetching the overall confusion matrix across all the folds.
